### ISSUE TITLE
Failed to install Dual Audio Builds

### ISSUE THREAD

**Issue by manosnoam** [LS80/script.openelec.devupdate#25]
Hi,
I've installed devupdate plugin, in order to add patch for dual audio in openelec.
However, trying to install it I get error:
File "/storage/.kodi/addons/script.openelec.devupdate/resources/lib/builds.py", line 96, in __init__
    self.release = [int(p) for p in version.split('.')]
ValueError: invalid literal for int() with base 10: '3-iPTD-Beta-2'

Here's ssh command output:

OpenELEC (unofficial) Version: 5.95.3-iPTD-Beta-2
OpenELEC:~ #
OpenELEC:~ # ./devupdate

[0] Official Snapshot Builds
[1] Milhouse Builds
[2] Official Releases
[3] Official Archive
[4] DarkAngel2401 Dual Audio Builds
--------------------------------------------------
Choose an item or "q" to quit: 4
/storage/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/util/ssl_.py:100: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/storage/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/util/ssl_.py:100: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/storage/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/util/ssl_.py:100: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/storage/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/util/ssl_.py:100: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/storage/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/util/ssl_.py:100: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "./devupdate", line 94, in <module>
    installed_build = builds.get_installed_build()
  File "/storage/.kodi/addons/script.openelec.devupdate/resources/lib/builds.py", line 440, in get_installed_build
    return Release(version)
  File "/storage/.kodi/addons/script.openelec.devupdate/resources/lib/builds.py", line 96, in __init__
    self.release = [int(p) for p in version.split('.')]
ValueError: invalid literal for int() with base 10: '3-iPTD-Beta-2'

**Comment by LS80** [comment]
What's this version you have installed? 5.95.3-iPTD-Beta-2 doesn't look familiar.
What hardware do you have?

**Comment by manosnoam** [comment]
My Kodi is on OpenElec, M8 Square device.

That's the firmware I have:
http://freaktab.com/forum/tv-player-support/amlogic-based-tv-players/eny-acemax-em8-square-em6q-etc-devices/491016-openelec-5-95-3-beta-2-eny-m8-2g-square-with-amcodec-boblightd-support
